[project]
name = "horariosautomatricula"
version = "0.1.0"
description = "Repositorio de Jorge Lombardo Bergillos de la asignatura IV 2024-25"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
